# Set exports
export GOPATH=$HOME/go
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$GOPATH/bin:/usr/local/go/bin
export WORKON_HOME=$HOME/.virtualenvs

export LC_ALL="en_US.utf-8"
export LANG="$LC_ALL" 

# Set default user
DEFAULT_USER="dkua"

# Set aliases
alias "tmux.new"="tmux new-session -s ${1}"
alias "tmux.kill"="tmux kill-session -t ${1}"
alias "tmux.attach"="tmux attach-session -t ${1}"
alias "tmux.list"="tmux list-sessions"
alias "tmux.nuke"="tmux kill-server"
alias "anaconda"="export PATH=$HOME/anaconda/bin:$PATH"
