#!/bin/sh
eval "$(/opt/homebrew/bin/brew shellenv)"

# Set exports
export EDITOR=vim
export LOCAL_BIN=$HOME/.local/bin
export HOMEBREW_PATHS=/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/bin/ruby/bin
export PATH=$LOCAL_BIN:$HOMEBREW_PATHS:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
export WORKON_HOME=$HOME/.virtualenvs
export LC_ALL="en_US.utf-8"
export LANG="$LC_ALL" 
export DOTFILES_DIR=$HOME/dotfiles
export SSH_AUTH_SOCK=$HOME/.ssh/agent

# Git-Completion exports
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_SHOWCOLORHINTS=1

# Set default user
DEFAULT_USER="dkua"

# Set aliases
alias "ibrew"="arch -x86_64 /usr/local/bin/brew"
alias "virtenv"="source /usr/local/bin/virtualenvwrapper.sh"
alias "rmi"="rm -i"
alias "docker.rmc"="docker_rmc"
alias "docker.rmi"="docker_rmi"
alias "vagrant.sup"="vagrant up && vagrant ssh"
alias "vagrant.pup"="vagrant reload --provision && vagrant ssh"
alias "vagrant.purr"="vagrant reload --provision"
alias "vagrant.nuke"="vagrant destroy -f"
alias "vi"="vim"
alias "vissh"="vi $HOME/.ssh/config"
alias ":q"="exit"
alias "python"="python3"

# Set some colours
GREEN="\[\e[0;32m\]"
BLUE="\[\e[0;34m\]"
RED="\[\e[0;31m\]"
YELLOW="\[\e[0;33m\]"
COLOREND="\[\e[00m\]"

ykadd() {
    ykman list --serials;
    ssh-add -l;
    ssh-add -D;
    ssh-add -e /opt/homebrew/lib/libykcs11.dylib || true;
    ssh-add -s /opt/homebrew/lib/libykcs11.dylib;
    ssh-add -l;
}

docker_rmc() {
    echo "deleting all Docker containers";
    docker rm `docker ps -a -q`;
}

docker_rmi() {
    echo "deleting all Docker images";
    docker rmi `docker images -q`;
}


# Source work specific stuff
[ -f $HOME/.work-profile ] && source $HOME/.work-profile

# Source box specific stuff
[ -f $HOME/.vm_profile ] && source $HOME/.vm_profile
. "$HOME/.cargo/env"
