#!/bin/sh

# Set exports
export EDITOR=vim
export GOPATH=$HOME/go
export ANACONDAPATH=$HOME/anaconda
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$GOPATH/bin:/usr/local/go/bin:/Applications/eclipse
export WORKON_HOME=$HOME/.virtualenvs
export CDPATH=$CDPATH:$GOPATH/src:$GOPATH/src/github.com/$USER:$GOPATH/src/github.com:$GOPATH/src/code.google.com/p:$WORKON_HOME
export LC_ALL="en_US.utf-8"
export LANG="$LC_ALL" 
export DOTFILES_DIR=$HOME/dotfiles

# Git-Completion exports
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_SHOWCOLORHINTS=1

# Set default user
DEFAULT_USER="dkua"

# Set aliases
alias "tmux.new"="tmux new-session -s ${1}"
alias "tmux.kill"="tmux kill-session -t ${1}"
alias "tmux.attach"="tmux attach-session -t ${1}"
alias "tmux.list"="tmux list-sessions"
alias "tmux.nuke"="tmux kill-server"
alias "anaconda"="export PATH=$ANACONDAPATH/bin:$PATH"
alias "virtenv"="source /usr/local/bin/virtualenvwrapper.sh"
alias "rmi"="rm -i"
alias "docker.rmc"="docker_rmc"
alias "docker.rmi"="docker_rmi"
alias "vagrant.sup"="vagrant up && vagrant ssh"
alias "vi"="vim"
alias "vissh"="vi $HOME/.ssh/config"

# Set some colours
GREEN="\[\e[0;32m\]"
BLUE="\[\e[0;34m\]"
RED="\[\e[0;31m\]"
YELLOW="\[\e[0;33m\]"
COLOREND="\[\e[00m\]"

goget () {
    if [ "$1" ]; then
        go get -u $1
    else
        echo "usage: goget <repo> <symlink folder>"
        return 1
    fi

    if [ "$2" ]; then
        ln -s $GOPATH/src/$1 $2
    else
        echo "nothing symlinked"
        return 1
    fi
    return 0
}

docker_rmc() {
    echo "deleting all Docker containers";
    docker rm `docker ps -a -q`;
}

docker_rmi() {
    echo "deleting all Docker images";
    docker rmi `docker images -q`;
}

# Source box specific stuff
[ -f $HOME/.vm_profile ] && source $HOME/.vm_profile
