#!/bin/zsh

setopt INTERACTIVE_COMMENTS

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/dkua/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Customize to your needs...

source $HOME/.profile

source $DOTFILES_DIR/shell/antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-completions src
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme minimal
antigen apply
